### ISSUE TITLE
different name between template and substitutions

### ISSUE THREAD

**Issue by jeonghanlee** [icshwi/ECMC_config#1]
Hi @kivel 

  It is  good to see you here. I would like to discuss name convention from some template files and the substitutions files. 
  For example, `ecmcEL7332.template` should be `ecmcEL7332_chX.template`, because we can inflating template and substitutions files together and EPICS base has no idea two outputs are different.  They will be the same name as `ecmcEL7332.db`.  That will make a lot of confusions and potential risks to point the different db file at the end.  
  Could you make the different name between template and substitutions file?

**Comment by kivel** [comment]
Hi Han

I totally agree and it's planned to be changed during the migration from ECMC 5.3 to 6.0.
In the past, I simply copied most of the templates and subs from ecmctraining and made minor adjustments.
Is ESS committed to using ECMC_config in production?

**Comment by jeonghanlee** [comment]
Yes, I was looking for the alternative one instead of ecmctraining. I think, your repo is the good one.

**Comment by jeonghanlee** [comment]
work with ecmccfg repo.
